"""empty message

Revision ID: 987e104dcecc
Revises: 
Create Date: 2022-05-31 13:03:21.225702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '987e104dcecc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('director',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('surname', sa.VARCHAR(), nullable=True),
    sa.Column('date_birth', sa.DATE(), nullable=True),
    sa.Column('wiki_url', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_director_id'), 'director', ['id'], unique=False)
    op.create_table('genre',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poster',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('url', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('enabled', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nickname', sa.VARCHAR(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('surname', sa.VARCHAR(), nullable=True),
    sa.Column('date_birth', sa.DATE(), nullable=True),
    sa.Column('date_registry', sa.DATE(), nullable=True),
    sa.Column('id_role', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_role'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nickname')
    )
    op.create_table('movie',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('date_release', sa.DATE(), nullable=True),
    sa.Column('rating', sa.NUMERIC(), nullable=True),
    sa.Column('id_director', sa.INTEGER(), nullable=True),
    sa.Column('id_poster', sa.INTEGER(), nullable=True),
    sa.Column('id_user', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_director'], ['director.id'], ),
    sa.ForeignKeyConstraint(['id_poster'], ['poster.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_id'), 'movie', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movie_id'), table_name='movie')
    op.drop_table('movie')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('poster')
    op.drop_table('genre')
    op.drop_index(op.f('ix_director_id'), table_name='director')
    op.drop_table('director')
    # ### end Alembic commands ###
