"""empty message

Revision ID: 3f167befd442
Revises: d41acf509109
Create Date: 2022-06-13 13:42:47.088010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f167befd442'
down_revision = 'd41acf509109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('director', 'date_birth',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('director', 'wiki_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('director', 'wiki_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('director', 'date_birth',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###