"""empty message

Revision ID: 619b76ea95b5
Revises: 
Create Date: 2022-06-06 08:24:42.008107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '619b76ea95b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('id_genre', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'movie', 'genre', ['id_genre'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movie', type_='foreignkey')
    op.drop_column('movie', 'id_genre')
    # ### end Alembic commands ###
