"""empty message

Revision ID: 65039aecadef
Revises: 3f167befd442
Create Date: 2022-06-13 13:45:27.469724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65039aecadef'
down_revision = '3f167befd442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('director', 'date_birth',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('director', 'wiki_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('director', 'wiki_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('director', 'date_birth',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
