"""empty message

Revision ID: d5955d166f46
Revises: 65039aecadef
Create Date: 2022-06-13 14:53:02.815691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5955d166f46'
down_revision = '65039aecadef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id_role',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id_role',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
