version: "3.9"

services:
  web:
    container_name: web-${APP_NAME}
    image: web-${APP_NAME}
    build: .
    ports:
      - "80:80"
    environment:
      - ./.env
    depends_on:
      - db

  db:
      image: postgres:14.2
      env_file:
          - ./.env
      restart: always
      container_name: db-${APP_NAME}
      hostname: db-${APP_NAME}
      environment:
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          PGDATA: /var/lib/postgresql/data
      volumes:
          - db-data:/var/lib/postgresql/data

volumes:
  db-data: